"""Primary Keys

Revision ID: b8145f562837
Revises: 
Create Date: 2023-01-18 15:19:51.188213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8145f562837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('catid', sa.SmallInteger(), nullable=False),
    sa.Column('catgroup', sa.String(length=10), nullable=True),
    sa.Column('catname', sa.String(length=10), nullable=True),
    sa.Column('catdesc', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('catid')
    )
    op.create_table('date',
    sa.Column('dateid', sa.SmallInteger(), nullable=False),
    sa.Column('caldate', sa.Date(), nullable=False),
    sa.Column('day', sa.CHAR(length=3), nullable=False),
    sa.Column('week', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.CHAR(length=5), nullable=False),
    sa.Column('qtr', sa.CHAR(length=5), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('holiday', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('dateid')
    )
    op.create_table('event',
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('venueid', sa.SmallInteger(), nullable=False),
    sa.Column('catid', sa.SmallInteger(), nullable=False),
    sa.Column('dateid', sa.SmallInteger(), nullable=False),
    sa.Column('eventname', sa.String(length=200), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('eventid')
    )
    op.create_table('listing',
    sa.Column('listid', sa.Integer(), nullable=False),
    sa.Column('sellerid', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('dateid', sa.SmallInteger(), nullable=False),
    sa.Column('numtickets', sa.SmallInteger(), nullable=False),
    sa.Column('priceperticket', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('totalprice', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('listtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('listid')
    )
    op.create_table('sales',
    sa.Column('salesid', sa.Integer(), nullable=False),
    sa.Column('listid', sa.Integer(), nullable=False),
    sa.Column('sellerid', sa.Integer(), nullable=False),
    sa.Column('buyerid', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('dateid', sa.SmallInteger(), nullable=False),
    sa.Column('qtysold', sa.SmallInteger(), nullable=False),
    sa.Column('pricepaid', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('saletime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('salesid')
    )
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.CHAR(length=8), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('state', sa.CHAR(length=2), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.CHAR(length=14), nullable=True),
    sa.Column('likesports', sa.Boolean(), nullable=True),
    sa.Column('liketheatre', sa.Boolean(), nullable=True),
    sa.Column('likeconcerts', sa.Boolean(), nullable=True),
    sa.Column('likejazz', sa.Boolean(), nullable=True),
    sa.Column('likeclassical', sa.Boolean(), nullable=True),
    sa.Column('likeopera', sa.Boolean(), nullable=True),
    sa.Column('likerock', sa.Boolean(), nullable=True),
    sa.Column('likevegas', sa.Boolean(), nullable=True),
    sa.Column('likebroadway', sa.Boolean(), nullable=True),
    sa.Column('likemusicals', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('venue',
    sa.Column('venueid', sa.SmallInteger(), nullable=False),
    sa.Column('venuename', sa.String(length=100), nullable=True),
    sa.Column('venuecity', sa.String(length=30), nullable=True),
    sa.Column('venuestate', sa.CHAR(length=2), nullable=True),
    sa.Column('venueseats', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('venueid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue')
    op.drop_table('users')
    op.drop_table('sales')
    op.drop_table('listing')
    op.drop_table('event')
    op.drop_table('date')
    op.drop_table('category')
    # ### end Alembic commands ###
